### ISSUE TITLE
Question: do we have to keep coming back here and download the new one every week?

### ISSUE THREAD

**Issue by CJStyles123** [lolmanurfunny/Roblox-Launcher-minus-the-app#1]
just a question i had for this, would appreciate a tool that automatically does this or something!

**Comment by lolmanurfunny** [comment]
Good idea. I will look into releasing such a tool.

**Comment by CJStyles123** [comment]
sounds good! take your time if needed. all this wouldn't need to happen if we could just opt-out of Beta like previously.

**Comment by nobleassass1n** [comment]
How does one run python? Also roblox released another update :')

**Comment by lolmanurfunny** [comment]
You need to download python to use the py script. I released an exe to make it more accessible, you should check that out as it doesn't require python to work.
