### ISSUE TITLE
404 when I try to access the RobloxPlayerLauncher.

### ISSUE THREAD

**Issue by actualjc2019** [lolmanurfunny/Roblox-Launcher-minus-the-app#14]
The 'lolmanurfunny/Roblox-Launcher-minus-the-app' repository doesn't contain the 'RobloxPlayerLauncher.exe' path in 'main'.

**Comment by SebammXD** [comment]
ur looking for this: https://github.com/lolmanurfunny/Roblox-Launcher-minus-the-app/releases/tag/CL-v1.0.1

**Comment by lolmanurfunny** [comment]
> The 'lolmanurfunny/Roblox-Launcher-minus-the-app' repository doesn't contain the 'RobloxPlayerLauncher.exe' path in 'main'.

v1.0.0 was discontinued!
