### ISSUE TITLE
Grapejuice does not execute the Launcher

### ISSUE THREAD

**Issue by Jarfeh** [lolmanurfunny/Roblox-Launcher-minus-the-app#18]
Hey there, I'm using Grapejuice in order to launch Roblox on linux, but for some reason it will not execute it no matter what I do.

**Comment by Jarfeh** [comment]
This likely isn't an issue with your launcher, just thought I'd mention it

**Comment by lolmanurfunny** [comment]
No idea why software wouldn't work on an OS it wasn't designed to work on. Anyhow, I have no experience outside of windows so I don't know how to help you with that problem besides saying "you could use it on a windows VM".
