### ISSUE TITLE
my name

### ISSUE THREAD

**Issue by ImStupidHehe** [lolmanurfunny/Roblox-Launcher-minus-the-app#19]
When i dowlload RobloxLaucher.exe this icon like python and i cant replace it how i can fix that .TY if i have a answer
![image](https://user-images.githubusercontent.com/114597858/192813343-f716a99c-9d36-46b5-a773-3eea0ea892d8.png)

**Comment by lolmanurfunny** [comment]
https://github.com/lolmanurfunny/Roblox-Launcher-minus-the-app#manual-instructions
