### ISSUE TITLE
Method patched.

### ISSUE THREAD

**Issue by aliftf2** [lolmanurfunny/Roblox-Launcher-minus-the-app#2]
### Dear, programmer. A method is patched by **ROBLOX** or something wrong with it, Microsoft. Defender. SmartScreen. lets **ROBLOX** to reinstall it's desktop app (BETA). which it lets **ROBLOX** to reinstall itself. M.D.SS (Microsoft. Defender. SmartScreen.) Can be disabled, but **ROBLOX** can still reinstall itself After this. That seems bad new. I don't know how to explain everything here.

`Truly,`
`- Epic man who stare at window.`

**Comment by CJStyles123** [comment]
roblox has updated again today sadly, not sure what their intent was or if they actually added more patches to make it harder for us to stop using this dumb rushed Desktop App.

**Comment by 2ddrr** [comment]
so annoying dude! we don't don't want this goofy roblox app and they still force us to use it. why does it gotta be so difficult to have an option to disable and enable it

**Comment by HexaRG** [comment]
it appears roblox removed all references to "InApp" and "InBrowser" in the launcher code, i think they've actually patched it for real now
![image](https://user-images.githubusercontent.com/67880600/192065601-106c0fca-371c-48e1-a878-8af23411eb25.png)
^ HxD failing to find "InApp", and here's proof it existed before
![image](https://user-images.githubusercontent.com/67880600/192065677-509f6967-bec3-4a51-aeee-a221a9361166.png)

**Comment by HexaRG** [comment]
however, i did find this
![HxD_5JhD7fO4FR](https://user-images.githubusercontent.com/67880600/192065855-427b1298-556e-40ca-9aa9-a22edf297976.png)

**Comment by Zoardedz** [comment]
they patched your method, for me the py script works, also the launcher patch just got updated so you can run the py script and it should disable the beta app

**Comment by zLudociel** [comment]
the patch works for me

**Comment by aliftf2** [comment]
I don't think, it's updated.

**Comment by lolmanurfunny** [comment]
It's updated and working as intended as of ~5 hours ago.
