### ISSUE TITLE
Method is patched with same one!

### ISSUE THREAD

**Issue by aliftf2** [lolmanurfunny/Roblox-Launcher-minus-the-app#23]
Hello, lolmanurfunny. ROBLOX are still patching your latest version. A same one that lets ROBLOX to reinstall itself. Ye, it's Microsoft Defender SmartScreen. It's used to reinstall ROBLOX. If you run administrator a Roblox Launcher minus the app, it will reinstall ROBLOX. Which is why method is patched with same one.

**Comment by aliftf2** [comment]
Nevermind! It's not patched, unlesss if it's running as administrator.

**Comment by CJStyles123** [comment]
thats why the source code states that it's running as administrator, just reinstall roblox and run the beta nabber script.

**Comment by CJStyles123** [comment]
also i recommend you close this issue now since your problem has been resolved
