### ISSUE TITLE
Patched i guess but goodluck

### ISSUE THREAD

**Issue by VoiderzX** [lolmanurfunny/Roblox-Launcher-minus-the-app#25]
![image](https://user-images.githubusercontent.com/114313973/192903770-8f29af98-f9dd-42a3-be38-cfcad53fc622.png)

Yikes does not work or patched but big W on the project.

**Comment by Redcarred2** [comment]
Can confirm this

**Comment by lolmanurfunny** [comment]
It's because you need to download roblox's proprietary launcher and get their new client (RobloxPlayerBeta.exe)

**Comment by lolmanurfunny** [comment]
https://setup.rbxcdn.com/version-a5b3a0b177fa44c5-Roblox.exe
