### ISSUE TITLE
removing the 5 second sleep

### ISSUE THREAD

**Issue by FFrutz** [lolmanurfunny/Roblox-Launcher-minus-the-app#26]
Does this HAVE to be here? Using this to get small servers on hidden links for games with no serverlist makes it still not possible because the 5 second sleep at the end of loading makes the timing impossible.

**Comment by lolmanurfunny** [comment]
Sure I'll release a version that has the sleep removed.

**Comment by lolmanurfunny** [comment]
> Using this to get small servers on hidden links for games with no serverlist

Not sure what you mean since the 5 second sleep comes after the launcher sends the launch data to RobloxPlayerBeta.exe.

**Comment by FFrutz** [comment]
> > Using this to get small servers on hidden links for games with no serverlist
> 
> Not sure what you mean since the 5 second sleep comes after the launcher sends the launch data to RobloxPlayerBeta.exe.

All I know is that it didn't work before, and now it does. Thank you very much.
