### ISSUE TITLE
crash when trying to play a game

### ISSUE THREAD

**Issue by TimBomb7** [lolmanurfunny/Roblox-Launcher-minus-the-app#28]
(video deleted cuz it shows my windows username)
i already reinstalled roblox to  %localappdata% 
replaced it with custom launcher

**Comment by TimBomb7** [comment]
![screenshot-user-images githubusercontent com-2022 09 29-14_48_13](https://user-images.githubusercontent.com/83193530/192959373-8750c342-f28f-4587-b092-282a88f541e5.png)

**Comment by lolmanurfunny** [comment]
What is the path of the launcher relative to ``%localappdata%``

**Comment by lolmanurfunny** [comment]
Nvm it's visible in the video.

**Comment by lolmanurfunny** [comment]
Do you have `RobloxPlayerBeta.exe` in the same directory as the launcher?

**Comment by TimBomb7** [comment]
yeah

![Annotation 2022-09-29 152411](https://user-images.githubusercontent.com/83193530/192966944-33d4bbbe-ab09-4fab-8c74-62471a896622.png)

**Comment by lolmanurfunny** [comment]
![image](https://user-images.githubusercontent.com/77128366/192986482-359326ff-2356-45ad-b4ce-b122682c8036.png)
![image](https://user-images.githubusercontent.com/77128366/192986739-05983146-945c-404d-b2d7-71f7df429e01.png)
Close call.

**Comment by TimBomb7** [comment]
dont
