### ISSUE TITLE
Its patched 😭 

### ISSUE THREAD

**Issue by CG5isthebest** [lolmanurfunny/Roblox-Launcher-minus-the-app#32]
I cant play roblox anymore 😭

**Comment by CG5isthebest** [comment]
It "cant locate latest client"

**Comment by zachariapopcorn** [comment]
You need to update it, download the Roblox installer, run it, and then recopy the custom launcher

**Comment by CG5isthebest** [comment]
No, ROBLOX LITREALLY INSTALLED TO MY PROGRAM FILES (X86) FOR ME

**Comment by lolmanurfunny** [comment]
Don't install roblox as admin, unless you plan to never use this custom launcher as I will never add support for UAC required directories.
