### ISSUE TITLE
Automatically update when needed

### ISSUE THREAD

**Issue by zachariapopcorn** [lolmanurfunny/Roblox-Launcher-minus-the-app#33]
Heya, love the resource that you've made, but can you make it where when it can't find the latest Roblox version (after finding Roblox\Versions) it automatically downloads the installer, runs that, and reinstalls itself?

This can mostly be of use for the people who don't know what they are doing (*cough cough*, #32)

**Comment by CG5isthebest** [comment]
Actually, its because my roblox files automatically wanted to install to Program Files (X86) when i didn't run it as admin.

**Comment by lolmanurfunny** [comment]
> This can mostly be of use for the people who don't know what they are doing

I'm not going to spoon-feed people who don't know how to use their own computer at one of the most basic levels, the filesystem.

**Comment by zachariapopcorn** [comment]
Eh true, if people don't know how to do this stuff, why even have a computer lol?
