### ISSUE TITLE
Launcher runs in the background when closed

### ISSUE THREAD

**Issue by j7hrs** [lolmanurfunny/Roblox-Launcher-minus-the-app#37]
Whenever I close the launcher (normally, through pressing X or Alt+F4ing), the player will keep on running in background until ended through Task Manager.

Specifically, the launcher I'm running is CL v1.1.1 (NOT installed through Patch Nabber!), while the Windows system is 11.

**Comment by CJStyles123** [comment]
that happens with the normal roblox launcher as well, not sure why Roblox does this. (basically what the custom launcher does it just carries the args from the roblox one to the custom one without triggering app function.)

**Comment by lolmanurfunny** [comment]
> that happens with the normal roblox launcher as well

yeah. There's no difference between my launcher and roblox's in terms of how it launches the game client.
