### ISSUE TITLE
Roblox Version Out of Date

### ISSUE THREAD

**Issue by nobleassass1n** [lolmanurfunny/Roblox-Launcher-minus-the-app#38]
Having issue with roblox being out of date. Pop-up reads quote "Your version of Roblox may be out of date. Please update Roblox and try again. Error Code: 280." Do I just reinstall the custom launcher or do I wait for an update?

**Comment by nobleassass1n** [comment]
WAIT NVM! Just saw the contigency plan, disregard my issue.

**Comment by MexicanBoberto** [comment]
Im having that same problem where it pops up and says "Your version of Roblox may be out of date. Please update Roblox and try again. Error Code: 280." and I have no idea how to fix it.

**Comment by Paindeluxe** [comment]
> Im having that same problem where it pops up and says "Your version of Roblox may be out of date. Please update Roblox and try again. Error Code: 280." and I have no idea how to fix it.

Did you already read this? https://github.com/lolmanurfunny/Roblox-Launcher-minus-the-app#please-read-before-opening-an-issue-thanks

**Comment by Zoardedz** [comment]
in my pull request, take the other file not the RobloxPatch.py and run it, should automatically update and install latest roblox.
