### ISSUE TITLE
Cannot uninstall Custom-Launcher.

### ISSUE THREAD

**Issue by aliftf2** [lolmanurfunny/Roblox-Launcher-minus-the-app#39]
Want go back to Desktop app? You cannot uninstall Custom-Launcher since is it made of python. You were able move or recovery this, This Launcher is out of date? Is this? What's wrong with?

**Comment by Zoardedz** [comment]
reinstall roblox 💀

**Comment by freakknoob** [comment]
bro it not work when i reinstall roblox it tp me to roblox games web

**Comment by Zoardedz** [comment]
whar

**Comment by lolmanurfunny** [comment]
> Want go back to Desktop app? You cannot uninstall Custom-Launcher since is it made of python. You were able move or recovery this, This Launcher is out of date? Is this? What's wrong with?

My launcher works, it does not need to be updated. What needs to be updated is your roblox version.
