### ISSUE TITLE
how to unistall this freaking virus

### ISSUE THREAD

**Issue by freakknoob** [lolmanurfunny/Roblox-Launcher-minus-the-app#41]
bro when i unistall the virus i keep get teleport to this hub someone fucking help me i cant even play anything in roblox again

**Comment by Paindeluxe** [comment]
Just reinstall Roblox delete this Roblox Launcher and reinstall it

**Comment by emotionalcrisom** [comment]
Try opening File Explorer and click on the bar with words under where it says 'Clipboard'. Then, paste %localappdata%/Roblox/Versions into it and you should find the files to delete. Delete all of them, then you should be able to reinstall Roblox again.
![image](https://user-images.githubusercontent.com/93696728/194429844-ab4b0be6-c8d6-4b05-a697-277ec753e5e3.png)

**Comment by freakknoob** [comment]
OH MY GOD
THANK YOU THANK YOU FINALLY I CAN PLAY ROBLOX

**Comment by freakknoob** [comment]
but the virus still in there how to remove it the virus still there and when i try unistall it teleport me to this hub

**Comment by freakknoob** [comment]
bc i want to use krnl ;-;

**Comment by freakknoob** [comment]
the virus still make my apps get stack click like auto click but it sometimes appeard sometimes not

**Comment by CJStyles123** [comment]
are you blind? where is this 'virus' you're talking about? do you not see the code is open-sourced? What can I expect from someone who uses krnl and not Synapse. 🤡

**Comment by foxxerss** [comment]
average roblox player

**Comment by Zoardedz** [comment]
average roblox player

**Comment by lolmanurfunny** [comment]
<img src="https://media.tenor.com/D1Ws8C4pZQAAAAAC/spongebob-patrick.gif">
