### ISSUE TITLE
malware

### ISSUE THREAD

**Issue by hissquare** [lolmanurfunny/Roblox-Launcher-minus-the-app#42]
delete this fucking repo you fucking tard

**Comment by Paindeluxe** [comment]
You can just look at the source code it’s not malware you incompetent little baby

**Comment by Zoardedz** [comment]
where tf is the malware, everything is open source and viewable, compile nonproperiatry roblox launcher if you'd like also agree with the guy abode

**Comment by CJStyles123** [comment]
You might be the dumbest person to create an issue here, nevertheless the code is open-sourced too. Incompetent fuck.

**Comment by hissquare** [comment]
I'll show screenshots you retards

**Comment by hissquare** [comment]
![image](https://user-images.githubusercontent.com/102501713/194797439-73b5d3fd-3183-47b6-87b8-b545915fb882.png)

appdata, tokens and steal def doesnt steal your tokens
dont be retarded.

**Comment by Paindeluxe** [comment]
This honestly just shows how dumb the average Roblox user is the code is here you didn’t look at it downloaded it, then accused it of being malware

**Comment by Paindeluxe** [comment]
I looked at the source code 2 times and guess what i didn’t see those words or urls and don’t say I didn’t look at it hard enough since there aren’t many .py files

**Comment by Paindeluxe** [comment]
And you also have forked token stealers in your repos tab so you aren’t trustworthy at all.

**Comment by CJStyles123** [comment]
> ![image](https://user-images.githubusercontent.com/102501713/194797439-73b5d3fd-3183-47b6-87b8-b545915fb882.png)
> 
> appdata, tokens and steal def doesnt steal your tokens dont be retarded.

so much for creating accusations whilst also having token stealers in your repo. I've read all the .py files in this repo and have not found anything to be suspicious. you shouldn't even be on this planet if you're gonna try and downgrade someone and their projects if there's nothing wrong or suspicious about it. dumbass.

**Comment by hissquare** [comment]
really now

i downloaded his "custom launcher"

there being a source code does not mean he hasn't compiled a different .py file.
look into the code if you can.

and yes. i have tried token logging my friends to send funny shit to all their friends.

**Comment by hissquare** [comment]
paindeluxe i have an open source python extractor repo, which indeed is not mine but you can look into the source and and confirm there is no malware there. from there you can download the custom launcher and extract the source code and see what you find.

**Comment by CJStyles123** [comment]
you're so stupid. the owner literally made a post on the DevForum showcasing this. you would think people would call him out if they found 'Malware' and his access to DevForum would be revoked leading him to be banned, right? stop spewing bullshit out your ass just because you love this Desktop app. No one's gonna side with someone that has suspicious repos in his profile.

would appreciate if someone revoked this guys access to creating issues further, so mediocre.

**Comment by lolmanurfunny** [comment]
> the owner literally made a post on the DevForum showcasing this.

Exactly. 💯
