### ISSUE TITLE
Same account launched from different device.

### ISSUE THREAD

**Issue by CG5isthebest** [lolmanurfunny/Roblox-Launcher-minus-the-app#44]
I'm trying to use V1.10 on a different PC but it says same account launched from different device.

**Comment by Paindeluxe** [comment]
Did you try to join immediately on a new device after leaving the game?

**Comment by CG5isthebest** [comment]
No. I realized it was just this one game.

**Comment by lolmanurfunny** [comment]
That happened to me the first time I was testing it, it was temporary and went away after I joined a different game. To this day I don't know the precise cause.

**Comment by CG5isthebest** [comment]
No, it happens every time i join the Realistic Forest Demo.

**Comment by lolmanurfunny** [comment]
Have you tried restarting your pc? It's worth a shot.
And maybe go into roblox's ``settings > Security``, and click this button:
![image](https://user-images.githubusercontent.com/77128366/195221048-51f0612a-a520-461a-b47a-930331c80bb2.png)

**Comment by CG5isthebest** [comment]
I have never gave away ANYTHING that gives ppl access to my acc, also i dont have access to the pc right now. My parents were letting me use their pc.

**Comment by lolmanurfunny** [comment]
> I have never gave away ANYTHING that gives ppl access to my acc

I haven't either, though it could be something on roblox's end making it think you're still in a game, which is why I suggested that it could be a step in the right direction.

**Comment by CG5isthebest** [comment]
Probabaly, i didn't have my roblox running on any other devices. I made sure to close out roblox on my main computer (thats like 2 years old)

**Comment by zachariapopcorn** [comment]
This sometimes happens when you have a "ghost" RobloxPlayerBeta.exe process still running in the background, try typing the following command in RUN (Win+R) and try again
``taskkill /f /im RobloxPlayerBeta.exe``

**Comment by Bloxxness** [comment]
This may happen when there is a newer version of Roblox and it is not saying "This is an older version of Roblox"

**Comment by aliftf2** [comment]
Woah, this was happened to me. I actually reinstalled Actual ROBLOX since ROBLOX thinks Custom Launcher is older version of ROBLOX. lolmanurfunny hasn't working on this launcher, So ROBLOX thinks custom Launcher is older version! I've been using my Computer since 2013-2014, and joined ROBLOX since 2017.

**Comment by Zoardedz** [comment]
> This may happen when there is a newer version of Roblox and it is not saying "This is an older version of Roblox"

:star:

**Comment by rageh20** [comment]
happened to me but ONE THIS one specific game, every other game works fine except the kool zone

**Comment by lolmanurfunny** [comment]
> lolmanurfunny hasn't working on this launcher, So ROBLOX thinks custom Launcher is older version!

That is inaccurate. The launcher is not 1:1 with roblox's updates. Since [CL-v1.0.0](https://github.com/lolmanurfunny/Roblox-Launcher-minus-the-app/releases/tag/CL-v1.0.0) I have not made any major alterations to the python script.

**Comment by zachariapopcorn** [comment]
When updating the client, perhaps because you have to reinstall it cause the update functionality gets removed, joining the same game that prompted the "Roblox version out of date" message before updating throws this error, and any other games work

Then again, I'm using a custom made batch script to automatically download and run the latest version of the installer (according to the zflag endpoint that this thing uses), so this just be my issue, can anyone reproduce?

**Comment by CG5isthebest** [comment]
@zachariapopcorn Can you send me the batch script?

**Comment by CG5isthebest** [comment]
@zachariapopcorn 

https://user-images.githubusercontent.com/81264672/197372058-fc262db6-576b-4dea-bb33-176aa969a4a9.mp4
^^, because you wont send the batch script

**Comment by CG5isthebest** [comment]
> 




https://user-images.githubusercontent.com/81264672/197372091-48739b7a-c335-4eed-bacd-727bdbdea318.mp4

**Comment by CG5isthebest** [comment]
> When updating the client, perhaps because you have to reinstall it cause the update functionality gets removed, joining the same game that prompted the "Roblox version out of date" message before updating throws this error, and any other games work
> 
> Then again, I'm using a custom made batch script to automatically download and run the latest version of the installer (according to the zflag endpoint that this thing uses), so this just be my issue, can anyone reproduce?

C a p , CAP https://user-images.githubusercontent.com/81264672/197372091-48739b7a-c335-4eed-bacd-727bdbdea318.mp4

**Comment by zachariapopcorn** [comment]
@CG5isthebest Can you like, shut the fuck up? Aren't you the same dumbass that thought this was patched and ran it as admin and thought it wasn't their fault? Learn to grow some fucking braincells and figure it out yourself, stupid child

**Comment by Bloxxness** [comment]
Bro calm down.

**Comment by zachariapopcorn** [comment]
@Bloxxness I will not tolerate being called cap by a script kiddie who I refused to spoon feed. He needs to learn that he can't ask people for code and get it 100% of the time, and if he doesn't get the code, he needs to learn to just deal with it. He may as well learn that now
