### ISSUE TITLE
Problems when Roblox release new updates.

### ISSUE THREAD

**Issue by Bloxxness** [lolmanurfunny/Roblox-Launcher-minus-the-app#48]
When Roblox has an update and I join a game, instead of updating the launcher it goes straight into the game. This leads to me not being able to play Roblox and instead have to uninstall Roblox, reinstall it with the newest version and then launching the Roblox minus the app, app. It would be great if this app automatically checked for updates from Roblox before going into the game.

**Comment by Zoardedz** [comment]
you can use the roblox betapp patch nabber from my pull request, it should fix the error for you since it automatically does what you just said.

**Comment by Dippcraft** [comment]
> you can use the roblox betapp patch nabber from my pull request, it should fix the error for you since it automatically does what you just said.

It did not

**Comment by Bloxxness** [comment]
Sorry but I don't see your pull request

**Comment by Zoardedz** [comment]
https://github.com/lolmanurfunny/Roblox-Launcher-minus-the-app/pull/31 heres the pull request if you cant see it https://github.com/Zoardedz/Roblox-Launcher-minus-the-app heres the source code if you wanna download it all
