### ISSUE TITLE
everytime i open a game it says that the same launched game from different device keeps popping up

### ISSUE THREAD

**Issue by rageh20** [lolmanurfunny/Roblox-Launcher-minus-the-app#49]
i tried reinstalling roblox but the error kept popping up can someone help?

**Comment by rageh20** [comment]
i tried reinstalling it but it kept popping up is this an error a bug?! wtf.

**Comment by Zoardedz** [comment]
update your roblox, go to my pull request fork and download the source make sure you have python installed, go to the python webpage and install python from there, after installing python open command prompt do pip install pyinstaller and press on robloxpatch.py, itll start doing some funky shit but at the end you can play roblox again
