### ISSUE TITLE
got stacked click in game because the virus still there

### ISSUE THREAD

**Issue by freakknoob** [lolmanurfunny/Roblox-Launcher-minus-the-app#50]
everytime i hold something in game ex: bow in bedwars the bow auto shoot 3 arrows

**Comment by lolmanurfunny** [comment]
<img src = "https://media.tenor.com/GLW-m3S5vjkAAAAd/broom-broom-horse.gif">

**Comment by localfossa** [comment]
...

**Comment by Zoardedz** [comment]
i do not understand what the fuck this means

**Comment by Zoardedz** [comment]
https://tenor.com/view/wwe-vince-mcmahon-gif-23421483

**Comment by Paindeluxe** [comment]
![4E67836C-8E62-4A1F-B5FC-31B3E9DC7ECA](https://user-images.githubusercontent.com/104042185/196030402-f827c909-d635-496b-832b-e0632d1cb434.gif)
