### ISSUE TITLE
Roblox not detecting Keyboard inputs

### ISSUE THREAD

**Issue by Paindeluxe** [lolmanurfunny/Roblox-Launcher-minus-the-app#51]
I don't understand why it happens but everytime I try to play [TC2](https://web.roblox.com/games/328028363/Typical-Colors-2) it just won't detect any input

I tried a external keyboard (I use a laptop) and still nothing...

**Comment by lolmanurfunny** [comment]
Try a different game and see if you still endure such issues.

**Comment by Paindeluxe** [comment]
Well looks like rejoining like a maniac fixes the problem?
