### ISSUE TITLE
Roblox returning a 264 error ( same account error) after installing the launcher and joining the game

### ISSUE THREAD

**Issue by TheTopHat26** [lolmanurfunny/Roblox-Launcher-minus-the-app#54]
After updating roblox and dowloding the launcher i get the same account error.
It's getting on my nerves  becouse if i join a diffrent game there's no sign of that error
And i don't know for how long the error stays but i always updated my client at night so after i wake up it's patched and i can play that game now.

IT"S LIKE A SOFTLOCK

**Comment by localfossa** [comment]
I know that you can't enter the last game. Just wait a few minutes and it will be solved. Roblox thinks that you are playing the game.

**Comment by miguelvf3** [comment]
is it the "same account launched from different device"  error? it happens on the same game but i was able to join a different one

**Comment by localfossa** [comment]
> is it the "same account launched from different device" error? it happens on the same game but i was able to join a different one

I found that it is happening on the normal launcher too. It is not related to custom launcher.

**Comment by lolmanurfunny** [comment]
> It is not related to custom launcher.

Thank god...
