### ISSUE TITLE
Ask user if they want to launch Roblox if Roblox is already running

### ISSUE THREAD

**Issue by zachariapopcorn** [lolmanurfunny/Roblox-Launcher-minus-the-app#56]
I think this will be a nice QOL update for people who accidently reload a private server link page or click on one by accident, and since it's not in the real launcher, why not add it?

**Comment by lolmanurfunny** [comment]
Why reinvent the wheel when you could've just not pressed the "Always open links of this type in the associated app" checkbox on your browser?

**Comment by zachariapopcorn** [comment]
I completely forgot about that feature

**Comment by lolmanurfunny** [comment]
All good!
