### ISSUE TITLE
roblox is not loading

### ISSUE THREAD

**Issue by ScriptLoader-BLACK-X** [lolmanurfunny/Roblox-Launcher-minus-the-app#57]
please fix this issues

**Comment by lolmanurfunny** [comment]
.... is this really all the info you're going to present me with about a problem you're having?

**Comment by Zoardedz** [comment]
lmfaoo

**Comment by WhiteTeam2020** [comment]
LOL

**Comment by lolmanurfunny** [comment]
https://user-images.githubusercontent.com/77128366/200154992-ba71e354-47b5-4ea8-a987-6af6e7fb6d0c.mp4
