### ISSUE TITLE
Cannot launch Roblox

### ISSUE THREAD

**Issue by spenkluker645** [lolmanurfunny/Roblox-Launcher-minus-the-app#6]
Launcher will output "[Error]: Unable to locate latest roblox client!"

**Comment by lolmanurfunny** [comment]
Make sure you have your Roblox installed here: **%localappdata%\Roblox\Versions\version-b117c4c276664452**

**Comment by CG5isthebest** [comment]
Im having the same issue, its not installed there. How do i get it to install there?

**Comment by CG5isthebest** [comment]
Roblox patched it

**Comment by lolmanurfunny** [comment]
> Roblox patched it

still works

**Comment by lolmanurfunny** [comment]
> Im having the same issue, its not installed there. How do i get it to install there?

That's what happens when you install roblox via running as admin.
