### ISSUE TITLE
The patcher got patched in the latest release

### ISSUE THREAD

**Issue by FurryMLG** [lolmanurfunny/Roblox-Launcher-minus-the-app#60]

**Comment by nobleassass1n** [comment]
Dear FurryMLG,
There is a contingency plan set just for this issue. Look for the "README.md" link on the main page here. Super simple instructions

**Comment by FurryMLG** [comment]
I'm using the patch nabber, and I followed all the instructions. I ran the script, nothing

**Comment by Paindeluxe** [comment]
Just delete roblox reinstall it then install this custom launcher

**Comment by FurryMLG** [comment]
I did.
It does nothing.

**Comment by lolmanurfunny** [comment]
>The patcher got patched in the latest release #60

Ah yes, I hate when roblox patches the ability to use your own computer's file system.
