### ISSUE TITLE
Launcher not working anymore

### ISSUE THREAD

**Issue by JC395248** [lolmanurfunny/Roblox-Launcher-minus-the-app#62]
Every time I launch Roblox with the custom launcher installed, it always launches the desktop app. I have tried re-installing Roblox countless times, restarting my computer, trying the patch nabber, but it all resulted in the desktop app launching regardless. I don't know what else to do, please help.

**Comment by ReconWxlf** [comment]
same thing happens to me
roblox most likely done something when they updated earlier

**Comment by lolmanurfunny** [comment]
Weird, I just joined a game <1 minute ago, worked flawlessly. Was it working as intended before the update?

**Comment by JC395248** [comment]
> Weird, I just joined a game <1 minute ago, worked flawlessly. Was it working as intended before the update?

Yes, it was working just fine before yesterday.

**Comment by JC395248** [comment]
Just now, I tried re-installing a fresh version of roblox and replacing the launcher with the custom one, but it still launches the desktop app. I have no idea what else to do.

**Comment by Absumm** [comment]
this is now happening to me as well

**Comment by Hasbeans** [comment]
Seem roblox now forces you to launch the desktop app again even with using the patcher

**Comment by lolmanurfunny** [comment]
Looking into it.

**Comment by lolmanurfunny** [comment]
Which means I have to fight goofy with goofy.

**Comment by ILoveArson** [comment]
happening for me too, worked fine earlier today
seems the update is being rolled out inconsistently, some people probably haven't gotten a prompt for an update yet

**Comment by lolmanurfunny** [comment]
[Hotfix released!](../releases/latest)

**Comment by JC395248** [comment]
> [Hotfix released!](../releases/latest)

How do I use the patch nabber? I don't think I used it correctly before.

**Comment by lolmanurfunny** [comment]
just run it

**Comment by JC395248** [comment]
I don't know if it worked or not, but for some reason, whenever I use alt f4 on Roblox, the game keeps running in the background until I go into task manager and stop it from running. This is very annoying, and I don't know how to fix it.

**Comment by lolmanurfunny** [comment]
> the game keeps running in the background until I go into task manager and stop it from running.

That's odd, I've never had that happen to me.
![image](https://user-images.githubusercontent.com/77128366/201260843-c79a21b0-5f3c-446d-921b-88dcaf47f1bb.png)

**Comment by JC395248** [comment]
It doesn't display it on the top for me, I have to scroll down until it shows it in alphabetical order.

**Comment by JC395248** [comment]
![Task Manager 11_10_2022 8_09_37 PM](https://user-images.githubusercontent.com/109009754/201261373-105c306d-0c53-43a4-b4cb-e56574d0856f.png)

**Comment by lolmanurfunny** [comment]
I'm unsure what the cause of that could be, other than crashing/freezing in a prior play session.

**Comment by JC395248** [comment]
This only happens if I close the program without returning to the home page on the desktop app.

**Comment by Car-Rampage** [comment]
![image](https://user-images.githubusercontent.com/117966870/201268200-d653a866-93ee-4706-93ff-ff9093beb0e3.png)
the roblox app buttons still appear
the home thing in the esc menu is whatever, but the top bar when you hover over it is annoying

**Comment by zachariapopcorn** [comment]
Kinda sad that Roblox is ignoring it's community on a big update like this one

**Comment by Strana** [comment]
Well shit, looks like I'm going on another temporary quit again!!!

Hopefully this can be fixed.

**Comment by XxBoomer** [comment]
![image](https://user-images.githubusercontent.com/28081360/201380250-23c22345-0ea7-413f-a247-480db5d1a371.png)
im already try reinstall roblox with administrator then rerun exe file but it still send me this error

**Comment by joaxzyscripts** [comment]
not working still

**Comment by XxBoomer** [comment]
hmm btw when in screen leave it old version then i leave it back to beta 
![image](https://user-images.githubusercontent.com/28081360/201400266-d8754865-adbb-4a87-b56b-b12e19d08be7.png)
![image](https://user-images.githubusercontent.com/28081360/201400280-9d3a5832-a67d-4fdd-8710-883408c12521.png)

**Comment by lolmanurfunny** [comment]
> rerun exe file

Specifying which exe would be helpful. @XxBoomer

**Comment by rageh20** [comment]
i reinstalled the patch nabber but when i joined the game nothing loaded up wth

**Comment by rageh20** [comment]
also i rerean the exe 2x

**Comment by lolmanurfunny** [comment]
Rerunning PN isn't gonna make it work all of a sudden, sadly.

**Comment by localfossa** [comment]
> ![image](https://user-images.githubusercontent.com/28081360/201380250-23c22345-0ea7-413f-a247-480db5d1a371.png) im already try reinstall roblox with administrator then rerun exe file but it still send me this error

The launcher is working for me. Install **without** running as administrator and make sure that you are using Patch Nabber.

**Comment by TehEpikNoobKing** [comment]
yeah same happens with me it just opens the beta app

**Comment by JC395248** [comment]
> > ![image](https://user-images.githubusercontent.com/28081360/201380250-23c22345-0ea7-413f-a247-480db5d1a371.png) im already try reinstall roblox with administrator then rerun exe file but it still send me this error
> 
> The launcher is working for me. Install **without** running as administrator.

I tried that before, but it still launches the beta app.

**Comment by CatzRule81** [comment]
I think Roblox might've patched us out.

**Comment by rageh20** [comment]
bruh

**Comment by rageh20** [comment]
so what do we do now?
![download](https://user-images.githubusercontent.com/115760541/201501370-3008b795-c2a4-41df-8167-4b0425276a06.jpg)

**Comment by localfossa** [comment]
> > > ![image](https://user-images.githubusercontent.com/28081360/201380250-23c22345-0ea7-413f-a247-480db5d1a371.png) im already try reinstall roblox with administrator then rerun exe file but it still send me this error
> > 
> > 
> > The launcher is working for me. Install **without** running as administrator.
> 
> I tried that before, but it still launches the beta app.



> > > ![image](https://user-images.githubusercontent.com/28081360/201380250-23c22345-0ea7-413f-a247-480db5d1a371.png) im already try reinstall roblox with administrator then rerun exe file but it still send me this error
> > 
> > 
> > The launcher is working for me. Install **without** running as administrator.
> 
> I tried that before, but it still launches the beta app.

Run the new patch nabber but it isn't an exe file.

**Comment by TheTopHat26** [comment]
### Oh man.
Roblox really sometimes pisses me off.
I must use this launcher i hate the beta app at one point it bricked explorer.exe. Yes i had a black screen and my mouse and keyboard turned off. The only thing that was runing was the fan.Seriusly!

Now i tried to use this it but it failed gave me a sign up page and then after i ran the exe roblox dosen't launch. why roblox just why.
**What's your fucking** point what do you think roblox? Why are you pushing, forcing it. It's so goddamn trash🗑️

Even the console dosen't have anything

![console](https://user-images.githubusercontent.com/115375073/201542086-592f944e-fa3a-4be6-9009-41a00ed240a3.png)

**Comment by JC395248** [comment]
@lolmanurfunny Any luck in finding a solution to this problem yet, or is Roblox still being stupid about it?

**Comment by zachariapopcorn** [comment]
The patch nabber seems to fix the issue for now

**Comment by miguelvf3** [comment]
it didnt for me

**Comment by e6blpb3eJleHcKoro** [comment]
Please help, I use the nabber patch, everything is installed normally, but when you run any mod, the version still remains 1.1.0, although the patch showed that version 1.1.1 was installed
The desktop application remains the same
