### ISSUE TITLE
Suggestion: Add custom prompt that tells you Roblox is outdated

### ISSUE THREAD

**Issue by zachariapopcorn** [lolmanurfunny/Roblox-Launcher-minus-the-app#66]
I know Roblox already does this when you launch the client, but for some reason, when updating when using the launcher, it seems to "softban" you from the last game that you joined before updating, saying that you've already launched the game on another device, which in my case, is false

I've tried everything that I can think of, but it seems that once the vanilla client tells you that it is outdated, that's when the softban occurs, so I think preventing the outdated client from launching should fix it

If you have another solution to this problem, may you please share?

**Comment by lolmanurfunny** [comment]
> it seems that once the vanilla client tells you that it is outdated, that's when the softban occurs

Didn't for me. I joined a baseplate to ensure the (custom) launcher was outdated. Then I had to update my roblox version. Was able to join back immediately, no notion of any sort of "softban" whatsoever.

**Comment by zachariapopcorn** [comment]
Huh, interesting, maybe it was just me? Idk

**Comment by lolmanurfunny** [comment]
It happened to me once, maybe twice before, it's quite intermittent.
