### ISSUE TITLE
Do you ignore pull requests?

### ISSUE THREAD

**Issue by localfossa** [lolmanurfunny/Roblox-Launcher-minus-the-app#68]
May you look #69? I made good changes.
I deleted #52 because code has been updated and I added new things you can look closed pr

**Comment by lolmanurfunny** [comment]
I already merged one of your past pull requests. You know the answer to this.

**Comment by lolmanurfunny** [comment]
I believe the reason I "ignored" one of your PRs was due to an update I pushed which shit on the mergeability of your PR.

**Comment by localfossa** [comment]
I opened this issue because 2 pull requests stayed for 21 days
