### ISSUE TITLE
roblox crashes

### ISSUE THREAD

**Issue by Zoardedz** [lolmanurfunny/Roblox-Launcher-minus-the-app#74]
when i open roblox with the new patch (which deletes the places and universalapp folders) it crashes my roblox

**Comment by lolmanurfunny** [comment]
Ok

**Comment by Zoardedz** [comment]
this is due to the mobile.rblx file not existing, i just wanted to clear that up (if im not mistaken)

**Comment by nahhhhhhhhhhhhhhhhhhh** [comment]
its happening to me too

**Comment by nahhhhhhhhhhhhhhhhhhh** [comment]
idk why roblox forces this stupid app thing

its useless.
.
.
.
.
.
..
.
.
.
..
.
..
.
.
.
..
.
.
.
.
.
..
.
.
.
..

.
..
.
.
.
.
.
.

**Comment by Zoardedz** [comment]
ikr

**Comment by ILoveArson** [comment]
same here, whenever i open the client it crashes, and the one time i got it to open without crashing leaving put me in the desktop app

**Comment by nahhhhhhhhhhhhhhhhhhh** [comment]
why cant they just bring back the disabling button

**Comment by Paindeluxe** [comment]
They already wasted a ton of money thats why

> why cant they just bring back the disabling button

**Comment by nahhhhhhhhhhhhhhhhhhh** [comment]
> They al

> They already wasted a ton of money thats why
> 
> > why cant they just bring back the disabling button

oh ok

**Comment by Zoardedz** [comment]
@lolmanurfunny the reason for this is that the launcher uses inBrowser and mobile.rbxl is missing, you should instead pair it with inApp and a missing mobile.rbxl. Yes the inApp launcher will still ask you to quit blah blah but it'll just crash instead of going to the homepage aswell as the main reason people are using this: the roblox player doesn't allocate memory or use your cpu for the initilization of the inapp homepage

**Comment by lolmanurfunny** [comment]
> the reason for this is that the launcher uses inBrowser

Wait, are you saying roblox's launcher does?

**Comment by Zoardedz** [comment]
no, this launcher

**Comment by newtV64** [comment]
Any news on the beta app patch?

**Comment by Zoardedz** [comment]
I think I know how to fix it but I'm too lazy so. Just go to the nonproperiatry launcher script and change inBrowser to inApp, yeah the beta app ui is there but when exiting roblox it doesn't bring you to the phone weird thingy and on the side of

**Comment by Zoardedz** [comment]
Reopened so that people know how to fix this.
