### ISSUE TITLE
can you please explain 

### ISSUE THREAD

**Issue by itsweekly** [lolmanurfunny/Roblox-Launcher-minus-the-app#8]
hey, so ima make a video on this since this has potential obviously giving you credit since what you made is pretty cool but could you explain how you modified the robloxplayerlauncher.exe

you can use any terms i know c++

**Comment by lolmanurfunny** [comment]
Before I made a custom launcher. I patched the vanilla RobloxPlayerLauncher.exe, removing the ``--app`` parameter so it would default to launching normally, not in the beta app.
